# @created: 05 Jan 2023
# @modified: 06 Jun 2023
# @author: Yoann Pradat
#
# This pipeline combines alterations (mutations, copy-number) annotated in OncoKB (https://www.oncokb.org/)
# and/or CIViC database (https://civicdb.org/home) and draws all plots that are based on these alterations.

include: "rules/common.smk"

##### Target rules #####

rule all:
    input:
        #### ALTERATIONS ####
        config["data"]["outputs"]["alterations_best"],
        config["data"]["outputs"]["alterations_all"],
        config["data"]["outputs"]["alterations"],
        expand("%s/alterations/alterations_{gene}_all.xlsx" % R_FOLDER, gene=["ERBB2", "SLX4", "PARG", "PIK3CA"]),
        #### ONCOPLOTS ####
        expand("%s/oncoplot/oncoplot_samples_{select}.pdf" % R_FOLDER, select=["all", "t1"]),
        expand("%s/oncoplot/oncoplot_subject_{subject}_{mode_amp}.pdf" % R_FOLDER,
            subject=["DAISY-109", "DAISY-173"], mode_amp=["wo_amp", "w_amp"]),
        expand("%s/oncoplot/oncoplot_t1vst2_diff_per_{alt_lvl}_{agg_mod}_{sel_mod}_{vaf_inc}.pdf" % R_FOLDER,
            alt_lvl=["gen","pth"], agg_mod=["v1", "v2", "v3"], sel_mod=["A","B"], vaf_inc=[0.2, 1])

##### Modules #####

include: "../common/rules/setup.smk"
include: "rules/aggregate.smk"
include: "rules/plotting.smk"

##### End messages #####

onsuccess:
    print("Workflow finished, no error")

onerror:
    print("An error occurred")
