setup:
  DAISY: ../../common/envs/DAISY.yaml
  DAISY_done: ../common/logs/setup_conda.done

data:
  inputs:
    cna_annotated: ../../../data/wes/somatic_cna/somatic_calls_union_ann.tsv.gz
    cna_pass: ../../../data/wes/somatic_cna/somatic_calls.tsv.gz
    cna_tcga_pass: ../../../data/wes/somatic_cna_tcga/somatic_calls.tsv.gz
    cln_curated: ../../../data/cln/curated/cln_daisy_curated.tsv
    cln_tcga_curated: ../../../data/cln/curated/cln_tcga_brca_curated.tsv
    drug: ../../../data/resources/drug_tables/Table_Drugs_v7.xlsx
    ids_curated: ../../../data/cln/curated/ids_daisy_curated.tsv
    ids_anonym: ../../../results/tables_paper/table_anonymisation.tsv
    mut_annotated: ../../../data/wes/somatic_maf/somatic_calls_union_ann.maf.gz
    mut_pass: ../../../data/wes/somatic_maf/somatic_calls.maf.gz
    mut_tcga_pass: ../../../data/wes/somatic_maf_tcga/somatic_calls.maf.gz
    pathways: ../../../data/resources/pathways/data/msigdb_pathways.tsv.gz
    sam_used: ../../../data/cln/curated/summary_samples_used.xlsx

  outputs:
    alterations_best: ../../../results/wes/alterations/aggregated_alterations_best.tsv
    alterations_all: ../../../results/wes/alterations/aggregated_alterations_all.tsv
    alterations: ../../../results/wes/alterations/aggregated_alterations.tsv
